/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 52f86fa3f92962c4af0640fd14d28087)
interface __BaseEnv_Env {
	JOURNAL_MANIFEST: DurableObjectNamespace<import("./src/index").JournalManifestDO>;
	FLEET_MANIFEST_CATALOG: DurableObjectNamespace<import("./src/index").FleetManifestCatalogDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "JournalManifestDO" | "FleetManifestCatalogDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
