/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/control-plane/wrangler.jsonc --include-runtime=false workers/control-plane/worker-configuration.d.ts` (hash: a921a92aa87b8de5a0bd0b8b2af194aa)
interface __BaseEnv_Env {
	JOURNAL_MANIFEST: DurableObjectNamespace<import("./src/index").JournalManifestDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "JournalManifestDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
