/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --config=workers/control-plane/wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 8a89190ece28793d3896ff2d5fcf46f8)
interface __BaseEnv_Env {
	DEPLOYMENT_FLEET_ID: "default";
	ADMIN_TOKEN: string;
	CATALOG: DurableObjectNamespace<import("./index").CatalogDO>;
	SHARD: DurableObjectNamespace<import("./index").ShardDO>;
	COORDINATOR: DurableObjectNamespace<import("./index").CoordinatorDO>;
	RESTORE_COORDINATOR: DurableObjectNamespace<import("./index").RestoreCoordinatorDO>;
	CONTROL_PLANE: Service<typeof import("../workers/control-plane/src/index").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "CatalogDO" | "ShardDO" | "CoordinatorDO" | "RestoreCoordinatorDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
