/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --config=workers/control-plane/wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 7147e231a0616b419967997cf07fc2a3)
interface __BaseEnv_Env {
	ADMIN_TOKEN: string;
	CATALOG: DurableObjectNamespace<import("./index").CatalogDO>;
	SHARD: DurableObjectNamespace<import("./index").ShardDO>;
	COORDINATOR: DurableObjectNamespace<import("./index").CoordinatorDO>;
	CONTROL_PLANE: Service<typeof import("../workers/control-plane/src/index").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "CatalogDO" | "ShardDO" | "CoordinatorDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
